name: 'Test'
description: 'Some action'
inputs:
  message:
    description: 'simple message'
    required: true
    default: 'Some-message...'
outputs:
  out:
    description: "test-out"
    value: ${{ steps.with-out.outputs.out }}

runs:
  using: "composite"
  steps:
    - name: Print message
      run: echo "$MSG"
      shell: bash
      env:
        MSG: ${{ inputs.message }}

    - name: Set output
      id: with-out
      shell: bash
      run: echo "out=out-from-action" >> $GITHUB_OUTPUT
    
